baseURL: https://iannimuliterno.github.io/blog2021/
languageCode: en
DefaultContentLanguage: en
title: config yaml draft do meu blog
theme: anatole
summarylength: 10
enableEmoji: yes
enableRobotsTXT: yes
publishDir: "docs/"
pygmentsUseClasses: yes
pygmentsCodeFences: yes
pygmentsCodefencesGuessSyntax: yes
disqusShortname: "@annymuliterno"

markup:
  goldmark:
    renderer:
      unsafe: true
